services:
  - name: backend
    build: ./backend
    port: 5050
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    depends_on:
      - mongodb
    networks:
      - mern_network

  - name: frontend
    build: ./frontend
    port: 5173
    environment:
      - REACT_APP_API_URL=http://backend:5050
    networks:
      - mern_network

  - name: mongodb
    image: mongo:latest
    port: 27017
    volumes:
      - mongo-data:/data/db
    networks:
      - mern_network

volumes:
  mongo-data:

networks:
  mern_network:
    driver: bridge
