services:
  backend:
    build: ./backend
    container_name: backend
    expose:
    - '5000'
  frontend:
    build: ./frontend
    container_name: frontend
    expose:
    - '80'
  nginx:
    depends_on:
    - frontend
    - backend
    image: nginx:latest
    ports:
    - 8080:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
version: '3'
