version: '3.8'
services:
  backend:
    container_name: backend
    expose:
    - '5050'
    ports:
    - 5050:5050
    build: ./backend
    depends_on:
    - mongodb
    environment:
    - MONGO_URI=mongodb://mongodb:27017/mydatabase
  frontend:
    container_name: frontend
    expose:
    - '5173'
    ports:
    - 5173:5173
    build: ./frontend
    environment:
    - REACT_APP_API_URL=http://backend:5050
  mongodb:
    container_name: mongodb
    expose:
    - '27017'
    ports:
    - 27017:27017
    image: mongo:latest
    volumes:
    - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local
